/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservieren;

import java.util.Date;
import java.util.Arrays;
import java.util.stream.Collectors;
/**
 *
 * @author X453SA
 */
public class showBookInfo extends javax.swing.JFrame {
    Date date = new Date();
    pasvar global = new pasvar();
    String result = Arrays.stream(global.showName).collect(Collectors.joining(" - "));
    
    /**
     * Creates new form showBookInfo
     */
    public showBookInfo() {
        initComponents();
        String dateText = date.toString();
        dates.setText(dateText);
        passengerName.setText(String.join("-", global.showName));
        invID.setText(String.join("-", global.showInvCode));
        noKTP.setText(String.join("-", global.showNoKtp));
        seat.setText(String.join("-", global.showSeat));
        classese.setText("");
        trName.setText(global.sepurName);
        hbf1.setText(global.from);
        hbf2.setText(global.to);
        departTime.setText(global.departTime);
        departDate.setText(global.date);
        System.out.println(global.showName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dates = new javax.swing.JLabel();
        jLabelz = new javax.swing.JLabel();
        jLabelz1 = new javax.swing.JLabel();
        jLabelz2 = new javax.swing.JLabel();
        passengerName = new javax.swing.JLabel();
        invID = new javax.swing.JLabel();
        noKTP = new javax.swing.JLabel();
        jLabelz3 = new javax.swing.JLabel();
        jLabelz4 = new javax.swing.JLabel();
        jLabelz5 = new javax.swing.JLabel();
        jLabelz6 = new javax.swing.JLabel();
        jLabelz7 = new javax.swing.JLabel();
        jLabelz8 = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();
        classese = new javax.swing.JLabel();
        trName = new javax.swing.JLabel();
        hbf1 = new javax.swing.JLabel();
        hbf2 = new javax.swing.JLabel();
        departTime = new javax.swing.JLabel();
        departDate = new javax.swing.JLabel();
        tktPrint = new javax.swing.JButton();
        jLabelz9 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Booking Results");

        jLabel2.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jLabel2.setText("Find your recent book activity here");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgsrc/30 dblogo.png"))); // NOI18N

        dates.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        dates.setText("date");

        jLabelz.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz.setText("Passenger Names :");

        jLabelz1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz1.setText("Booking IDs :");

        jLabelz2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz2.setText("Identification Number :");

        passengerName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        passengerName.setText("0");

        invID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        invID.setText("0");

        noKTP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        noKTP.setText("0");

        jLabelz3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz3.setText("Seat :");

        jLabelz4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz4.setText("Train Name :");

        jLabelz5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz5.setText("Departure Station :");

        jLabelz6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz6.setText("Arrival Station :");

        jLabelz7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz7.setText("Departure Time :");

        jLabelz8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelz8.setText("Class :");

        seat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        seat.setText("0");

        classese.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        classese.setText("0");

        trName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        trName.setText("0");

        hbf1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        hbf1.setText("0");

        hbf2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        hbf2.setText("0");

        departTime.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        departTime.setText("0");

        departDate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        departDate.setText("0");

        tktPrint.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tktPrint.setText("Print Ticket");
        tktPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tktPrintActionPerformed(evt);
            }
        });

        jLabelz9.setFont(new java.awt.Font("Roboto", 2, 10)); // NOI18N
        jLabelz9.setText("Please Remember the Booking IDs of each passenger as this value is used to print your tickets later");

        Exit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelz9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tktPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classese))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hbf2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hbf1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noKTP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passengerName))
                    .addComponent(dates)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(dates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz)
                    .addComponent(passengerName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz1)
                    .addComponent(invID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz2)
                    .addComponent(noKTP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz3)
                    .addComponent(seat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz8)
                    .addComponent(classese))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz4)
                    .addComponent(trName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz5)
                    .addComponent(hbf1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz6)
                    .addComponent(hbf2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelz7)
                    .addComponent(departTime)
                    .addComponent(departDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabelz9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tktPrint)
                    .addComponent(Exit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tktPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tktPrintActionPerformed
        new TktPrnt().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_tktPrintActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
        new dbzugticket.DBMainMenu().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showBookInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showBookInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel classese;
    private javax.swing.JLabel dates;
    private javax.swing.JLabel departDate;
    private javax.swing.JLabel departTime;
    private javax.swing.JLabel hbf1;
    private javax.swing.JLabel hbf2;
    private javax.swing.JLabel invID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelz;
    private javax.swing.JLabel jLabelz1;
    private javax.swing.JLabel jLabelz2;
    private javax.swing.JLabel jLabelz3;
    private javax.swing.JLabel jLabelz4;
    private javax.swing.JLabel jLabelz5;
    private javax.swing.JLabel jLabelz6;
    private javax.swing.JLabel jLabelz7;
    private javax.swing.JLabel jLabelz8;
    private javax.swing.JLabel jLabelz9;
    private javax.swing.JLabel noKTP;
    private javax.swing.JLabel passengerName;
    private javax.swing.JLabel seat;
    private javax.swing.JButton tktPrint;
    private javax.swing.JLabel trName;
    // End of variables declaration//GEN-END:variables
}
