/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservieren;

import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author X453SA
 */
public class TktPrnt extends javax.swing.JFrame {
    Connection con;
    Statement stmt,stmt1,stmt2,stmt3,stmt4,stmt5,stmt6,stmt7;
    ResultSet rs = null,rs1 = null,rs2 = null,rs3 = null,rs4 = null, rs5 = null,
              rs6 = null, rs7 = null;
    String tkt_id,cust_id,tr_id,cls_id,date_depart,time_depart,from,to,name,
            identification,train_name,showFrom,showTo,showClass;
    Integer invId;
    /**
     * Creates new form TktPrnt
     */
    public TktPrnt() {
        initComponents();
        connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        getInv = new javax.swing.JTextField();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Insert your Invoice ID Below to Print your Ticket");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Ticket Print");

        getInv.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        print.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        print.setText("Print");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getInv, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(print)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void connectDB(){
        try {
            Class.forName("com.mysql.jdbc.Driver");  
            con = DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/trendb","akar","akarpohon");  
            stmt = con.createStatement();
            stmt1 = con.createStatement();
            stmt2 = con.createStatement();
            stmt3 = con.createStatement();
            stmt4 = con.createStatement();
            stmt5 = con.createStatement();
            stmt6 = con.createStatement();
            stmt7 = con.createStatement();
        }catch(Exception e){
            System.out.println(e);
        }    
        
    }
    public void getResultSet(){
        try{
            invId = Integer.valueOf(getInv.getText());
   
            rs = stmt.executeQuery("SELECT ticket_id,cust_id FROM invoice WHERE invoice_id=" + invId.toString());
            rs.next();
            tkt_id = rs.getString(1);
            cust_id = rs.getString(2);
            
            rs1 = stmt1.executeQuery("SELECT tr_id,cls_id,date_depart,time_depart,std_id,sta_id FROM ticket WHERE tkt_id=" + tkt_id);
            rs1.next();
            tr_id = rs1.getString(1);
            cls_id = rs1.getString(2);
            date_depart = rs1.getString(3);
            time_depart = rs1.getString(4);
            from = rs1.getString(5);
            to = rs1.getString(6);
            
            rs2 = stmt2.executeQuery("SELECT name,identification FROM customer WHERE cust_id=" + cust_id);
            rs2.next();
            name = rs2.getString(1);
            identification = rs2.getString(2);
           
            rs3 = stmt3.executeQuery("SELECT name FROM series WHERE series_id=" + tr_id);
            rs3.next();
            train_name = rs3.getString(1);
            
            rs4 = stmt4.executeQuery("SELECT name FROM station WHERE st_id = " + from);
            rs4.next();
            showFrom = rs4.getString(1);
            
            rs5 = stmt5.executeQuery("SELECT name FROM station WHERE st_id = " + to);
            rs5.next();
            showTo = rs5.getString(1);
            
            rs6 = stmt6.executeQuery("SELECT name FROM class WHERE cls_id = " + cls_id);
            rs6.next();
            showClass = rs6.getString(1);
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Book ID Not Found !");
        }
    }
    
    public void printTkt (){
        String html = "<!DOCTYPE html><html><head> <title>DB TICKETS</title> <link href='https://fonts.googleapis.com/css?family=Lobster|Kreon:400,700' rel='stylesheet' type='text/css'> <link rel=\"stylesheet\" href=\"http://localhost/project/main.css\" media=\"screen\" charset=\"utf-8\"/> <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"> <meta http-equiv=\"content-type\" content=\"text-html; charset=utf-8\"></head><body> <div class=\"container\"> <section> <div class=\"circle\"> <div class=\"event\">Deutsche Bahn</div><div class=\"title\">"+ train_name +"<br />" + showFrom + " - " +showTo +"</div></div><div class=\"special\"></div><div class=\"special\"></div><div class=\"special\"></div><div class=\"special\"> <div class=\"seats\"> <span class=\"label\">section</span><span>A<!--SECTION PUT HERE LATER--></span> </div></div><div class=\"special\"> <div class=\"seats\"> <span class=\"label\">row</span><span>3<!--SEAT ROW NUMBER HERE LATER--></span> </div>" + name +" - "+ identification +"</div><div class=\"special\"> <div class=\"seats\"> <span class=\"label\">Class</span><span class=\"label\">" + showClass + "</span> </div>" + date_depart + " - " + time_depart +"<HERE></HERE> </div></section> <aside> <figure> <img src=\"http://localhost/project/dblogoweb.png\" alt=\"\"> </figure> </aside> </div></body></html>";
        new File("D:\\result").mkdir();
        File newHtml = new File("D:\\result\\ticket.html");
        try{
            BufferedWriter bw = new BufferedWriter(new FileWriter(newHtml));
            bw.write(html);
            bw.close();
            JOptionPane.showMessageDialog(this, "Ticket Printed!");
        } catch (IOException e){
            e.printStackTrace();
        }
        if (!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(this, "Desktop Not Supported");
            return;
        }
        
        Desktop desktop = Desktop.getDesktop();
        if(newHtml.exists()){
            try{
                desktop.open(newHtml);
            }catch (IOException r){
                r.printStackTrace();
            }   
        }
    }
    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        getResultSet();
        printTkt();        
        // TODO add your handling code here:
    }//GEN-LAST:event_printMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TktPrnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TktPrnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TktPrnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TktPrnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TktPrnt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField getInv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
